# Generated by Django 3.1.3 on 2020-11-09 05:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.CharField(blank=True, default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expireTime', models.DateTimeField()),
                ('isDeleted', models.BooleanField(default=False)),
                ('isFree', models.BooleanField(default=True)),
                ('isUnblocked', models.BooleanField(default=True)),
                ('deleteTime', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
