# Generated by Django 3.1.3 on 2020-11-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokenapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='deleteTime',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='expireTime',
            field=models.DateTimeField(blank=True),
        ),
    ]
