# Generated by Django 3.1.3 on 2020-11-09 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenapi', '0003_auto_20201109_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='isUnblocked',
        ),
    ]
